services:
  valkey:
    image: valkey/valkey:8.1.1-alpine
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - DATABASE_URL=sqlite+aiosqlite:///./db.sqlite3
      - PYTHONPATH=/app/src
      - UV_HTTP_TIMEOUT=60s
    volumes:
      - .:/app
      - /app/src/simple_online_taxi/__pycache__
      - /app/.venv
    depends_on:
      - valkey
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: development
    container_name: vue-frontend
    ports:
      - "5173:5173"
      - "8080:8080"
    environment:
      - VITE_API_URL=http://backend:8000/api
    volumes:
      - ./src/frontend:/app
    depends_on:
      - backend
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  valkey_data:

networks:
  app-network:
    driver: bridge
