"""add address to trips

Revision ID: 553f245cbd99
Revises: e8dc3133e344
Create Date: 2025-05-15 16:24:39.639550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553f245cbd99'
down_revision: Union[str, None] = 'e8dc3133e344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('from_address', sa.String(length=50), nullable=True))
    op.add_column('trips', sa.Column('to_address', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'to_address')
    op.drop_column('trips', 'from_address')
    # ### end Alembic commands ###
